service: typescript-aws-dynamodb

provider:
  name: aws
  runtime: nodejs6.10
  profile: devProfile
  region: ap-northeast-2
  environment:
    STAGE: ${self:custom.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:ap-northeast-2:*"

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-webpack

custom:
  stage: ${opt:stage, self:provider.stage}

functions:
  dynamo-tutorial:
    handler: handler.mainHandler
    memorySize: 128
    events:
      - http:
          path: tutorial/hello
          method: get
      - http:
          path: tutorial/create
          method: get

resources:
  Resources:
    UserEvent:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stage}-UserEvent
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
